commandsideservice:
  build: ./goal-service/
  restart: unless-stopped
  ports:
    - "8081:8080"

querysideservice:
  build: ./goal-view-service/
  restart: unless-stopped
  ports:
    - "8082:8080"
